import operator
from typing import Annotated, List, TypedDict

"""
AgentState: Defines the shared state structure for the LangGraph agent.

This state is passed between all nodes (planner, researcher, responder) 
and persisted across conversation turns using SQLite checkpointing.
"""

class AgentState(TypedDict):
    topic: str     # The current research topic/query from the user
    plan: List[str]     # List of search queries generated by the planner node
    findings: List[str]     # Research results collected by the researcher node (reset each turn)
    messages: Annotated[List[str], operator.add]    # Conversation history 
    current_step: int    # Tracks which step of the plan is currently being executed

